# configuration for develop/CI branch

-
  branches:
    only:
      - develop
      - master

  skip_tags: true
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU

  pull_requests:
    do_not_increment_build_number: false

  install:
    - choco install gitversion.portable -pre -y
    - nuget restore src

  before_build:
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo

  build:
    verbosity: minimal

  after_build:

  cache:
    - src\packages -> **\packages.config
    # - '%USERPROFILE%\.nuget\packages -> **\project.json'

  artifacts:
    - path: \src\bin\Release\
      name: Kaxaml.v$(GitVersion_AssemblySemVer)
      type: zip
